GET http://localhost:3000/comments HTTP/1.1

###

GET http://localhost:3000/comments?parentId=679bdf205c3d509ae270e05c HTTP/1.1

###

POST http://localhost:3000/comments HTTP/1.1
content-type: application/json

{
    "text": "First comment",
    "userId": "",
    "parentId": ""
}